Repository CommunityToolkit/Aspire, pull requests merged in 2024-10, with the labels that each got.

#98 Data API Builder Integration
  Aspire.CommunityToolkit.sln
  Directory.Packages.props
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.AppHost/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.AppHost.csproj
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.AppHost/Program.cs
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.AppHost/Properties/launchSettings.json
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.AppHost/appsettings.json
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.AppHost/dab-config.json
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.AppHost/sql-server/configure-db.sh
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.AppHost/sql-server/entrypoint.sh
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp.csproj
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/Components/App.razor
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/Components/Layout/MainLayout.razor
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/Components/Layout/MainLayout.razor.css
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/Components/Layout/NavMenu.razor
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/Components/Layout/NavMenu.razor.css
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/Components/Pages/Error.razor
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/Components/Pages/Home.razor
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/Components/Routes.razor
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/Components/_Imports.razor
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/Program.cs
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/Properties/launchSettings.json
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/TrekApiClient.cs
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/appsettings.json
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/wwwroot/app.css
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/wwwroot/bootstrap/bootstrap.min.css
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/wwwroot/bootstrap/bootstrap.min.css.map
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.BlazorApp/wwwroot/favicon.png
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.ServiceDefaults/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.ServiceDefaults.csproj
  examples/data-api-builder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.ServiceDefaults/Extensions.cs
  examples/data-api-builder/database/create_database.sql
  src/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.csproj
  src/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder/DataApiBuilderContainerImageTags.cs
  src/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder/DataApiBuilderContainerResource.cs
  src/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder/DataApiBuilderHostingExtension.cs
  src/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder/PublicAPI.Shipped.txt
  src/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder/PublicAPI.Unshipped.txt
  src/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder/README.md
  tests/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.Tests/AppHostTests.cs
  tests/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.Tests/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.Tests.csproj
  tests/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder.Tests/ContainerResourceCreationTests.cs
Labels: integration

#100 Updating workload manifest before install Aspire in Workflows
  .devcontainer/post-create.sh
  .github/workflows/dotnet-ci.yml
  .github/workflows/dotnet-main.yml
  .github/workflows/dotnet-release.yml
Labels: enhancement

#120 Adding Azure artifacts nuget feed to publishing
  .github/workflows/dotnet-ci.yml
  .github/workflows/dotnet-main.yml
  CONTRIBUTING.md
  README.md
  docs/faq.md
  docs/versioning.md
Labels: blocking-clean-ci

#66 Add Meilisearch integration
  CODEOWNERS
  CommunityToolkit.Aspire.sln
  Directory.Build.props
  Directory.Packages.props
  examples/meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.ApiService/CommunityToolkit.Aspire.Hosting.Meilisearch.ApiService.csproj
  examples/meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.ApiService/Movie.cs
  examples/meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.ApiService/Program.cs
  examples/meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.ApiService/Properties/launchSettings.json
  examples/meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.ApiService/appsettings.json
  examples/meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.AppHost/CommunityToolkit.Aspire.Hosting.Meilisearch.AppHost.csproj
  examples/meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.AppHost/Program.cs
  examples/meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.AppHost/Properties/launchSettings.json
  examples/meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.AppHost/appsettings.json
  examples/meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.ServiceDefaults/CommunityToolkit.Aspire.Hosting.Meilisearch.ServiceDefaults.csproj
  examples/meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.ServiceDefaults/Extensions.cs
  nuget.config
  src/CommunityToolkit.Aspire.Hosting.Meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.csproj
  src/CommunityToolkit.Aspire.Hosting.Meilisearch/MeilisearchBuilderExtensions.cs
  src/CommunityToolkit.Aspire.Hosting.Meilisearch/MeilisearchContainerImageTags.cs
  src/CommunityToolkit.Aspire.Hosting.Meilisearch/MeilisearchResource.cs
  src/CommunityToolkit.Aspire.Hosting.Meilisearch/PublicAPI.Shipped.txt
  src/CommunityToolkit.Aspire.Hosting.Meilisearch/PublicAPI.Unshipped.txt
  src/CommunityToolkit.Aspire.Hosting.Meilisearch/README.md
  src/CommunityToolkit.Aspire.Meilisearch/AspireMeilisearchExtensions.cs
  src/CommunityToolkit.Aspire.Meilisearch/CommunityToolkit.Aspire.Meilisearch.csproj
  src/CommunityToolkit.Aspire.Meilisearch/MeilisearchClientSettings.cs
  src/CommunityToolkit.Aspire.Meilisearch/MeilisearchHealthCheck.cs
  src/CommunityToolkit.Aspire.Meilisearch/PublicAPI.Shipped.txt
  src/CommunityToolkit.Aspire.Meilisearch/PublicAPI.Unshipped.txt
  src/CommunityToolkit.Aspire.Meilisearch/README.md
  src/CommunityToolkit.Aspire.OllamaSharp/README.md
  src/HealthChecksExtensions.cs
  src/PasswordGenerator.cs
  tests/CommunityToolkit.Aspire.Hosting.Meilisearch/AddMeilisearchTests.cs
  tests/CommunityToolkit.Aspire.Hosting.Meilisearch/AppHostTests.cs
  tests/CommunityToolkit.Aspire.Hosting.Meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.Tests.csproj
  tests/CommunityToolkit.Aspire.Hosting.Meilisearch/MeilisearchFunctionalTests.cs
  tests/CommunityToolkit.Aspire.Hosting.Meilisearch/MeilisearchPublicApiTests.cs
  tests/CommunityToolkit.Aspire.Meilisearch.Tests/AspireMeilisearchClientExtensionsTest.cs
  tests/CommunityToolkit.Aspire.Meilisearch.Tests/CommunityToolkit.Aspire.Meilisearch.Tests.csproj
  tests/CommunityToolkit.Aspire.Meilisearch.Tests/ConfigurationTests.cs
  tests/CommunityToolkit.Aspire.Meilisearch.Tests/ConformanceTests.cs
  tests/CommunityToolkit.Aspire.Meilisearch.Tests/MeilisearchClientPublicApiTests.cs
  tests/CommunityToolkit.Aspire.Meilisearch.Tests/MeilisearchContainerFixture.cs
  tests/CommunityToolkit.Aspire.Testing/CommunityToolkit.Aspire.Testing.csproj
  tests/CommunityToolkit.Aspire.Testing/ConformanceTests.cs
  tests/CommunityToolkit.Aspire.Testing/DockerUtils.cs
  tests/CommunityToolkit.Aspire.Testing/ResourceLoggerForwarderService.cs
  tests/CommunityToolkit.Aspire.Testing/TestDistributedApplicationBuilder.cs
  tests/CommunityToolkit.Aspire.Testing/Xunit/ConditionalFactAttribute.cs
  tests/CommunityToolkit.Aspire.Testing/Xunit/ConditionalFactDiscoverer.cs
  tests/CommunityToolkit.Aspire.Testing/Xunit/ConditionalTheoryAttribute.cs
  tests/CommunityToolkit.Aspire.Testing/Xunit/ConditionalTheoryDiscoverer.cs
  tests/CommunityToolkit.Aspire.Testing/Xunit/ITestCondition.cs
  tests/CommunityToolkit.Aspire.Testing/Xunit/OSSkipConditionAttribute.cs
  tests/CommunityToolkit.Aspire.Testing/Xunit/OperatingSystems.cs
  tests/CommunityToolkit.Aspire.Testing/Xunit/SkippedTestCase.cs
  tests/CommunityToolkit.Aspire.Testing/Xunit/TestMethodExtensions.cs
  tests/CommunityToolkit.Aspire.Testing/Xunit/WORKAROUND_SkippedDataRowTestCase.cs
  tests/Directory.Build.props
Labels: integration

#129 Removing deprecated API
  examples/ollama/CommunityToolkit.Aspire.Hosting.Ollama.AppHost/Program.cs
  src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResourceBuilderExtensions.cs
  src/CommunityToolkit.Aspire.Hosting.Ollama/PublicAPI.Unshipped.txt
Labels: integration

#136 ignore artifact publishing when its depndabot
  .github/workflows/dotnet-ci.yml
Labels: blocking-clean-ci

#151 Enforcing XML docs
  .editorconfig
  Directory.Build.props
  src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaApiEndpointAnnotation.cs
  src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaAppEndpointAnnotation.cs
  src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaAppHostingExtension.cs
  src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaResource.cs
  src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaResourceOptions.cs
  src/CommunityToolkit.Aspire.Hosting.Golang/GolangAppExecutableResource.cs
  src/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions/NodeJSHostingExtensions.cs
  src/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions/NodePackageInstaller.cs
  src/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions/NpmPackageInstallerLifecycleHook.cs
  src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResource.cs
  src/CommunityToolkit.Aspire.OllamaSharp/AspireOllamaSharpExtensions.cs
  src/Directory.Build.props
Labels: documentation

#137 Feat add deno support
  .devcontainer/devcontainer.json
  .github/workflows/dotnet-ci.yml
  .github/workflows/dotnet-main.yml
  .github/workflows/dotnet-release.yml
  CommunityToolkit.Aspire.sln
  examples/deno/CommunityToolkit.Aspire.Hosting.Deno.AppHost/CommunityToolkit.Aspire.Hosting.Deno.AppHost.csproj
  examples/deno/CommunityToolkit.Aspire.Hosting.Deno.AppHost/Program.cs
  examples/deno/CommunityToolkit.Aspire.Hosting.Deno.AppHost/Properties/launchSettings.json
  examples/deno/CommunityToolkit.Aspire.Hosting.Deno.AppHost/appsettings.json
  examples/deno/CommunityToolkit.Aspire.Hosting.Deno.Apphost/CommunityToolkit.Aspire.Hosting.Deno.Apphost.csproj
  examples/deno/CommunityToolkit.Aspire.Hosting.Deno.Apphost/Program.cs
  examples/deno/CommunityToolkit.Aspire.Hosting.Deno.Apphost/Properties/launchSettings.json
  examples/deno/CommunityToolkit.Aspire.Hosting.Deno.Apphost/appsettings.json
  examples/deno/oak-demo/deno.json
  examples/deno/oak-demo/deno.lock
  examples/deno/oak-demo/main.ts
  examples/deno/vite-demo/.gitignore
  examples/deno/vite-demo/.vscode/extensions.json
  examples/deno/vite-demo/README.md
  examples/deno/vite-demo/deno.json
  examples/deno/vite-demo/deno.lock
  examples/deno/vite-demo/index.html
  examples/deno/vite-demo/public/vite-deno.svg
  examples/deno/vite-demo/public/vite.svg
  examples/deno/vite-demo/src/App.css
  examples/deno/vite-demo/src/App.tsx
  examples/deno/vite-demo/src/assets/react.svg
  examples/deno/vite-demo/src/index.css
  examples/deno/vite-demo/src/main.tsx
  examples/deno/vite-demo/src/vite-env.d.ts
  examples/deno/vite-demo/vite.config.ts
  examples/nodejs-ext/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions.AppHost/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions.AppHost.csproj
  src/CommunityToolkit.Aspire.Hosting.Deno/CommunityToolkit.Aspire.Hosting.Deno.csproj
  src/CommunityToolkit.Aspire.Hosting.Deno/DenoAppHostingExtensions.cs
  src/CommunityToolkit.Aspire.Hosting.Deno/DenoAppResource.cs
  src/CommunityToolkit.Aspire.Hosting.Deno/DenoPackageInstaller.cs
  src/CommunityToolkit.Aspire.Hosting.Deno/DenoPackageInstallerLifecycleHook.cs
  src/CommunityToolkit.Aspire.Hosting.Deno/PathNormalizer.cs
  src/CommunityToolkit.Aspire.Hosting.Deno/PublicAPI.Shipped.txt
  src/CommunityToolkit.Aspire.Hosting.Deno/PublicAPI.Unshipped.txt
  src/CommunityToolkit.Aspire.Hosting.Deno/README.md
  src/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions/NodeJSHostingExtensions.cs
  tests/CommunityToolkit.Aspire.Hosting.Deno.Tests/AppHostTests.cs
  tests/CommunityToolkit.Aspire.Hosting.Deno.Tests/CommunityToolkit.Aspire.Hosting.Deno.Tests.csproj
  tests/CommunityToolkit.Aspire.Hosting.Deno.Tests/ResourceCreationTests.cs
Labels: enhancement, integration

#155 backport ollama api change
  examples/ollama/CommunityToolkit.Aspire.Hosting.Ollama.AppHost/Program.cs
  src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResourceBuilderExtensions.cs
  src/CommunityToolkit.Aspire.Hosting.Ollama/PublicAPI.Unshipped.txt
Labels: integration

#161 Update README.md
  src/CommunityToolkit.Aspire.Hosting.Azure.DataApiBuilder/README.md
Labels: documentation

#166 Caching global npm packages
  .github/workflows/dotnet-ci.yml
  .github/workflows/dotnet-main.yml
  .github/workflows/dotnet-release.yml
Labels: blocking-clean-ci

#163 Fixing a readme that said component not integration
  src/CommunityToolkit.Aspire.Hosting.Ollama/CommunityToolkit.Aspire.Hosting.Ollama.csproj
  src/CommunityToolkit.Aspire.Meilisearch/README.md
Labels: documentation, integration

#165 Improving SWA test stability
  tests/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps.Tests/SwaHostingComponentTests.cs
Labels: flaky-test

#180 Update `ToolkitMinorVersion` to 0
  Directory.Build.props
Labels: bug

#183 Add Waitfor For Meilisearch
  examples/meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.AppHost/Program.cs
  src/CommunityToolkit.Aspire.Hosting.Meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.csproj
  src/CommunityToolkit.Aspire.Hosting.Meilisearch/MeilisearchBuilderExtensions.cs
  tests/CommunityToolkit.Aspire.Hosting.Meilisearch/MeilisearchFunctionalTests.cs
Labels: enhancement

#184 Code Coverage improvements
  .github/workflows/code-coverage.yml
Labels: blocking-clean-ci

#175 SWA health checks
  examples/swa/CommunityToolkit.Aspire.StaticWebApps.AppHost/Program.cs
  src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaAppHostingExtension.cs
  tests/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps.Tests/ResourceCreationTests.cs
  tests/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps.Tests/SwaHostingComponentTests.cs
Labels: integration
