Repository CommunityToolkit/Aspire, pull requests merged in 2025-01, with the labels that each got.

#372 SQLite integrations
  CommunityToolkit.Aspire.sln
  Directory.Packages.props
  README.md
  examples/sqlite/CommunityToolkit.Aspire.Sqlite.Api/BloggingContext.cs
  examples/sqlite/CommunityToolkit.Aspire.Sqlite.Api/CommunityToolkit.Aspire.Sqlite.Api.csproj
  examples/sqlite/CommunityToolkit.Aspire.Sqlite.Api/Migrations/20250107054253_InitialCreate.Designer.cs
  examples/sqlite/CommunityToolkit.Aspire.Sqlite.Api/Migrations/20250107054253_InitialCreate.cs
  examples/sqlite/CommunityToolkit.Aspire.Sqlite.Api/Migrations/BloggingContextModelSnapshot.cs
  examples/sqlite/CommunityToolkit.Aspire.Sqlite.Api/Program.cs
  examples/sqlite/CommunityToolkit.Aspire.Sqlite.Api/Properties/launchSettings.json
  examples/sqlite/CommunityToolkit.Aspire.Sqlite.Api/appsettings.json
  examples/sqlite/CommunityToolkit.Aspire.Sqlite.AppHost/CommunityToolkit.Aspire.Sqlite.AppHost.csproj
  examples/sqlite/CommunityToolkit.Aspire.Sqlite.AppHost/Program.cs
  examples/sqlite/CommunityToolkit.Aspire.Sqlite.AppHost/Properties/launchSettings.json
  examples/sqlite/CommunityToolkit.Aspire.Sqlite.AppHost/appsettings.json
  examples/sqlite/CommunityToolkit.Aspire.Sqlite.ServiceDefaults/CommunityToolkit.Aspire.Sqlite.ServiceDefaults.csproj
  examples/sqlite/CommunityToolkit.Aspire.Sqlite.ServiceDefaults/Extensions.cs
  src/CommunityToolkit.Aspire.Hosting.Sqlite/CommunityToolkit.Aspire.Hosting.Sqlite.csproj
  src/CommunityToolkit.Aspire.Hosting.Sqlite/PublicAPI.Shipped.txt
  src/CommunityToolkit.Aspire.Hosting.Sqlite/PublicAPI.Unshipped.txt
  src/CommunityToolkit.Aspire.Hosting.Sqlite/README.md
  src/CommunityToolkit.Aspire.Hosting.Sqlite/SqliteContainerImageTags.cs
  src/CommunityToolkit.Aspire.Hosting.Sqlite/SqliteResource.cs
  src/CommunityToolkit.Aspire.Hosting.Sqlite/SqliteResourceBuilderExtensions.cs
  src/CommunityToolkit.Aspire.Hosting.Sqlite/SqliteWebResource.cs
  src/CommunityToolkit.Aspire.Microsoft.Data.Sqlite/AspireSqliteExtensions.cs
  src/CommunityToolkit.Aspire.Microsoft.Data.Sqlite/CommunityToolkit.Aspire.Microsoft.Data.Sqlite.csproj
  src/CommunityToolkit.Aspire.Microsoft.Data.Sqlite/PublicAPI.Shipped.txt
  src/CommunityToolkit.Aspire.Microsoft.Data.Sqlite/PublicAPI.Unshipped.txt
  src/CommunityToolkit.Aspire.Microsoft.Data.Sqlite/README.md
  src/CommunityToolkit.Aspire.Microsoft.Data.Sqlite/SqliteConnectionSettings.cs
  src/CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite/AspireEFSqliteExtensions.cs
  src/CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite/CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite.csproj
  src/CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite/PublicAPI.Shipped.txt
  src/CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite/PublicAPI.Unshipped.txt
  src/CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite/README.md
  src/CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite/SqliteEntityFrameworkCoreSettings.cs
  src/Shared/ConnectionStringValidation.cs
  src/Shared/EntityFrameworkUtils.cs
  tests/CommunityToolkit.Aspire.Hosting.Sqlite.Tests/AddSqliteTests.cs
  tests/CommunityToolkit.Aspire.Hosting.Sqlite.Tests/AppHostTests.cs
  tests/CommunityToolkit.Aspire.Hosting.Sqlite.Tests/CommunityToolkit.Aspire.Hosting.Sqlite.Tests.csproj
  tests/CommunityToolkit.Aspire.Microsoft.Data.Sqlite.Tests/CommunityToolkit.Aspire.Microsoft.Data.Sqlite.Tests.csproj
  tests/CommunityToolkit.Aspire.Microsoft.Data.Sqlite.Tests/ConfigurationTests.cs
  tests/CommunityToolkit.Aspire.Microsoft.Data.Sqlite.Tests/ConformanceTests.cs
  tests/CommunityToolkit.Aspire.Microsoft.Data.Sqlite.Tests/SqliteConnectionTests.cs
  tests/CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite.Tests/CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite.Tests.csproj
  tests/CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite.Tests/ConfigurationTests.cs
  tests/CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite.Tests/ConformanceTests.cs
  tests/CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite.Tests/SqliteConnectionTests.cs
  tests/CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite.Tests/TestDbContext.cs
  tests/CommunityToolkit.Aspire.Testing/ConformanceTests.cs
Labels: integration

#348 Java app build extension
  examples/java/CommunityToolkit.Aspire.Hosting.Java.AppHost/CommunityToolkit.Aspire.Hosting.Java.AppHost.csproj
  examples/java/CommunityToolkit.Aspire.Hosting.Java.AppHost/Program.cs
  src/CommunityToolkit.Aspire.Hosting.Java/CommunityToolkit.Aspire.Hosting.Java.csproj
  src/CommunityToolkit.Aspire.Hosting.Java/JavaAppHostingExtension.Container.cs
  src/CommunityToolkit.Aspire.Hosting.Java/JavaAppHostingExtension.Executable.cs
  src/CommunityToolkit.Aspire.Hosting.Java/JavaAppHostingExtension.cs
  src/CommunityToolkit.Aspire.Hosting.Java/MavenBuildAnnotation.cs
  src/CommunityToolkit.Aspire.Hosting.Java/MavenOptions.cs
  src/CommunityToolkit.Aspire.Hosting.Java/PublicAPI.Unshipped.txt
  tests/CommunityToolkit.Aspire.Hosting.Java.Tests/ExecutableResourceCreationTests.cs
Labels: integration, Stale

#409 Stale issue workflow improvements
  .github/workflows/remove-stale-label.yml
  .github/workflows/stale-issues.yml
Labels: Stale

#427 Remove FA usage from docs
  docs/create-integration.md
Labels: documentation
